blank_issues_enabled: false
contact_links:
  - name: 🗨 Discussions
    url: https://github.com/revanced/revanced-suggestions/discussions
    about: Have something unspecific to ReVanced Website in mind? Search for or start a new discussion!